import pygame
from script import load_image
enemy_image = pygame.image.load('image/enemy/right.png').convert_alpha()
bottom_image = pygame.image.load('image/tile map/bottom.png').convert_alpha()
top_image = pygame.image.load('image/tile map/top.png').convert_alpha()
left_image = pygame.image.load('image/tile map/left.png').convert_alpha()
right_image = pygame.image.load('image/tile map/right.png').convert_alpha()
bush_tile1_image = pygame.image.load('image/tile map/bush_tile 1.png').convert_alpha()
bush_tile_tower_image = pygame.image.load('image/tile map/bush_tile_tower.png').convert_alpha()
tower_image = load_image('image/tower 1/tower')
of_image = pygame.image.load('image/tower 1/1_of.png').convert_alpha()
on_image = pygame.image.load('image/tower 1/1_on.png').convert_alpha()
bullet1_image = pygame.image.load('image/tower 1/bullet 1.png').convert_alpha()
tower_lvl_2_image = load_image('image/tower 1_1/tower')
bullet2_image = pygame.image.load('image/tower 1_1/bullet 2.png').convert_alpha()
panel_image = pygame.image.load('image/panel.jpg').convert_alpha()
upgrade_image = pygame.image.load('image/upgrade.png').convert_alpha()
grass_tile_1_image = pygame.image.load('image/tile map/grass_tile_1.png').convert_alpha()